namespace SigmaDraconis.Shared
{
    public enum ColonistEventType
    {
        None = 0,
        Arrival = 1,
        ReadyToWake = 2,
        StartSleepOutside = 10,
        StartSleepFirstNight = 11,
        StartSleepNoPod = 12,
        StartSleep = 13,
        EndSleep = 20,
        EndSleepOwnPod = 21,
        EndSleepNoPod = 22,
        EndSleepOutside = 23,
        SleptCold = 24,
        SleptHot = 25,
        AteNewLike = 30,
        AteNewDislike = 31,
        AteNewNeutral = 32,
        AteLike = 33,
        AteDislike = 34,
        GoodMood1 = 40,
        GoodMood2 = 41,
        BadMood1 = 50,
        BadMood2 = 51,
        Hot1 = 60,
        Hot2 = 61,
        Cold1 = 70,
        Cold2 = 71,
        FoodLacksVariety = 80,
        FoodLikeButLacksVariety = 81,
        FoodGoodVariety = 82,
        FoodDislikeLacksVariety = 83,
        Welcome = 90,
        Death = 95,
        NewResourceFound = 100,
        ImprovedResourceFound = 101,
        ScannerResourceFound = 105,
        HadWalk = 110,
        Relaxing = 111,
        TalkedWith = 120,
        ImprovedKek = 130,
        ProjectComplete = 200,
        WorkloadLow = 300,
        WorkloadModerate = 301,
        WorkloadHigh = 302,
        WorkloadExtreme = 303
    }
}
